server:
  port: 5000
  servlet:
    context-path: /minesweeper

spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

auth:
  jwt:
    secret: "minesweeper-api-core-user"
    # BCrypted on -> https://www.javainuse.com/onlineBcrypt
    secret-pass: "$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6"
    #Expiration in seconds
    token-expiration: 900

general:
  settings:
    difficulty-level: 0.35